### ISSUE TITLE
Control Zone 2 or 3

### ISSUE THREAD

**Issue by DerGrafausB** [saxn-paule/pimatic-onkyo-avr#1]
Hi,

how are the commands for Zone 2 & 3.
I have an pioneer lx-901.

Bye

Chris

**Comment by saxn-paule** [comment]
The only implemented commands are documented in the README.MD

If you could provide the RAW Commands from the vendor of your AVR I could extend the implementation.

**Comment by DerGrafausB** [comment]
Hi,

i found yesterday evening this commands.
All are in the xlsx file.
Did you get the attachment?

See you

Chris

Edit by saxn-paule: Removed visible email address and other needless stuff

**Comment by DerGrafausB** [comment]
Here is a download link

https://www.snapav.com/wcsstore/ExtendedSitesCatalogAssetStore/attachments/documents/Pioneer/ManualsAndGuides/Pioneer%20Serial%20AVR_101P%20Protocol.xlsx



Edit by saxn-paule: Removed visible email address and other needless stuff

**Comment by saxn-paule** [comment]
I got it, thank you.

I'll have a look on it and try to find a clean solution for supporting multiple zones.

**Comment by DerGrafausB** [comment]
Perfect. Thank you


Edit by saxn-paule: Removed visible email address and other needless stuff

**Comment by saxn-paule** [comment]
I just added the multizone commands and extended the readme file. You'll need to use the `send command "[group].[command]" to {device-id}` action with the new commands.

Could you please download and change the https://github.com/saxn-paule/pimatic-onkyo-avr/blob/master/lib/onkyo.js/onkyo.commands.js file, restart pimatic and test it?

**Comment by DerGrafausB** [comment]
I will check it tomorrow.
Thank you for your fast response

Edit by saxn-paule: Removed visible email address and other needless stuff

**Comment by saxn-paule** [comment]
@DerGrafausB Any updates?

**Comment by DerGrafausB** [comment]
Some commands work
Some don’t work

I will check them at the weekend
And send you a list

Edit by saxn-paule: Removed visible email address and other needless stuff

**Comment by saxn-paule** [comment]
@DerGrafausB Any updates?

**Comment by DerGrafausB** [comment]
Hi,

sorry that it took so longe time.
I checked the commands.

I found one missing point in your readme
Zone1

  *   SOURCE_SELECT.TV is not in the readme but it works

Zone2 & Zone3 works perfect, but the volume up, down & mute commands does not work.
The commands are right in your command.js i think.
Could it be that ther is a problem with the VOLUME Group?


Bye

Chris

**Comment by saxn-paule** [comment]
Thank you for the feedback.
I changed the commands and removed the whitespaces. Could you please test again.


### Multi zone support (replace X by zone number)
*handling the volume*
* ZONEX_AUDIO.MUTE
* ZONEX_AUDIO.UNMUTE
* ZONEX_AUDIO.MUTE_QSTN
* ZONEX_AUDIO.VOL_UP
* ZONEX_AUDIO.VOL_DOWN
* ZONEX_AUDIO.VOL_UP1
* ZONEX_AUDIO.VOL_DOWN1


Please keep in mind, that the audio commands differ to zone 1, because for zone 1 there are some special functions that allow changing the volume without sending raw commands.

**Comment by DerGrafausB** [comment]
I will check it after work in the evening

Von meinem iPhone gesendet

Am 30.07.2018 um 07:39 schrieb saxn-paule <notifications@github.com<mailto:notifications@github.com>>:


Thank you for the feedback.
I changed the commands and removed the whitespaces. Could you please test again.

Multi zone support (replace X by zone number)

handling the volume

  *   ZONEX_AUDIO.MUTE
  *   ZONEX_AUDIO.UNMUTE
  *   ZONEX_AUDIO.MUTE_QSTN
  *   ZONEX_AUDIO.VOL_UP
  *   ZONEX_AUDIO.VOL_DOWN
  *   ZONEX_AUDIO.VOL_UP1
  *   ZONEX_AUDIO.VOL_DOWN1

**Comment by DerGrafausB** [comment]
Hi,

good job. Now all 3 Zones works perfect.

It is not so importent, but one last question, do you know the command for zone1 vol.up1?

If i can help you, to check more, tell me.

Thank you very much.

Bye

DerGrafausB

Von: saxn-paule <notifications@github.com>
Gesendet: Montag, 30. Juli 2018 07:39
An: saxn-paule/pimatic-onkyo-avr <pimatic-onkyo-avr@noreply.github.com>
Cc: Christian Graf <Mail@christian-graf.de>; Mention <mention@noreply.github.com>
Betreff: Re: [saxn-paule/pimatic-onkyo-avr] Control Zone 2 or 3 (#1)


Thank you for the feedback.
I changed the commands and removed the whitespaces. Could you please test again.

Multi zone support (replace X by zone number)

handling the volume

  *   ZONEX_AUDIO.MUTE
  *   ZONEX_AUDIO.UNMUTE
  *   ZONEX_AUDIO.MUTE_QSTN
  *   ZONEX_AUDIO.VOL_UP
  *   ZONEX_AUDIO.VOL_DOWN
  *   ZONEX_AUDIO.VOL_UP1
  *   ZONEX_AUDIO.VOL_DOWN1

**Comment by saxn-paule** [comment]
I added some commands for zone 1 too, to be consistent with zone 2 and 3.

*handling the volume*
* VOLUME.DOWN
* VOLUME.UP
* VOLUME.MUTE
* VOLUME.UNMUTE
* AUDIO.MUTE
* AUDIO.UNMUTE
* AUDIO.MUTE_QSTN
* AUDIO.VOL_UP
* AUDIO.VOL_DOWN
* AUDIO.VOL_UP1
* AUDIO.VOL_DOWN1

*getting the current volume*
* AUDIO.Volume
* AUDIO.VOL_QSTN

**Comment by DerGrafausB** [comment]
It works. GOOD JOB!

Thank You

Cu

DerGrafausB

Von: saxn-paule <notifications@github.com>
Gesendet: Mittwoch, 1. August 2018 08:27
An: saxn-paule/pimatic-onkyo-avr <pimatic-onkyo-avr@noreply.github.com>
Cc: Christian Graf <Mail@christian-graf.de>; Mention <mention@noreply.github.com>
Betreff: Re: [saxn-paule/pimatic-onkyo-avr] Control Zone 2 or 3 (#1)


I added some commands for zone 1 too, to be consistent with zone 2 and 3.

handling the volume

  *   VOLUME.DOWN
  *   VOLUME.UP
  *   VOLUME.MUTE
  *   VOLUME.UNMUTE
  *   AUDIO.MUTE
  *   AUDIO.UNMUTE
  *   AUDIO.MUTE_QSTN
  *   AUDIO.VOL_UP
  *   AUDIO.VOL_DOWN
  *   AUDIO.VOL_UP1
  *   AUDIO.VOL_DOWN1

getting the current volume

  *   AUDIO.Volume
  *   AUDIO.VOL_QSTN

**Comment by saxn-paule** [comment]
released new tag/version v0.2.0

**Comment by DerGrafausB** [comment]
Just for information, i have a pioneer lx-901 Receiver

Von meinem iPhone gesendet

Am 02.08.2018 um 07:53 schrieb saxn-paule <notifications@github.com<mailto:notifications@github.com>>:


Closed #1<https://github.com/saxn-paule/pimatic-onkyo-avr/issues/1>.
